apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.8.2
      helm:
        values: |
          grafana.ini:
            server:
              domain: grafana.walborn.cloud
              serve_from_sub_path: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - "grafana.walborn.cloud"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
