apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: jellyfin
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.1.0
      helm:
        values: |
          persistence:
            media:
              size: 5Gi
          volumeMounts:
            - name: library
              mountPath: /library
          volumes:
            - name: library
              nfs:
                server: 10.0.1.1
                path: /nfs/media/
                readOnly: true

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin