{
 "title": "Kubernetes Nodes",
 "description": "Kubernetes Nodes for node exporter 0.16+ (via Prometheus)\r\n",
 "tags": [
  "nodes",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(nodename)" } }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", node=\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{node=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{node=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{node=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$server\"} - node_memory_MemFree_bytes{node=\"$server\"} - node_memory_Buffers_bytes{node=\"$server\"} - node_memory_Cached_bytes{node=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{node=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{node=\"$server\"} - node_memory_MemFree_bytes{node=\"$server\"}  - node_memory_Buffers_bytes{node=\"$server\"} - node_memory_Cached_bytes{node=\"$server\"}) / node_memory_MemTotal_bytes{node=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_nfsd_disk_bytes_read_total{node=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (node) (rate(node_nfsd_disk_bytes_written_total{node=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (node) (rate(node_disk_io_time_seconds_total{node=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",node=\"$server\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",node=\"$server\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",node=\"$server\"})"
    }
   ]
  },
  {
   "title": "Pods on Node (Count)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$server\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 21 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{node=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Node CPU Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(sensor) (node_hwmon_temp_celsius{node=\"$server\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}